# Generated by Django 4.1.7 on 2023-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='stats',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'InActive'), ('L', 'Latest'), ('R', 'Recipe of the Day')], max_length=1),
        ),
    ]
