# Generated by Django 4.1.7 on 2023-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'InActive'), ('F', 'Featured Member')], max_length=1, null=True),
        ),
    ]
